version: '3.4'

services:
  customerapi:
    container_name: customer-api
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: CustomerAPI/Dockerfile
    environment:
        - DB_HOST=customerdb
        - DB_NAME=customer
        - DB_SA_PASSWORD=Sql1234321
    ports:
        - 8001:80
    depends_on:
        - customerdb

  customerdb:
    container_name: customer-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Sql1234321
    ports:
        - 1451:1433

  productapi:
    container_name: product-api
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: ProductAPI/Dockerfile
    environment:
        - DB_HOST=productdb
        - DB_NAME=product
        - DB_SA_PASSWORD=Sql1234321
    ports:
        - 8002:80
    depends_on:
        - productdb

  productdb:
    container_name: product-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Sql1234321
    ports:
        - 1452:1433

  orderapi:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: OrderAPI/Dockerfile
    environment:
        - DB_HOST=orderdb
        - DB_NAME=order
    ports:
        - 8003:80
    depends_on:
        - orderdb

  orderdb:
    container_name: order-db
    image: mongo
    ports:
        - 18005:27017
